version: '3.8'

name: 4cite

services:
  postgres:
    image: postgres:13-alpine
    networks: [app]
    environment:
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_DATABASE}'
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
networks:
  app:

volumes:
  data:
